### ISSUE TITLE
禁用了左键，但是经常出现双击并选中的操作

### ISSUE THREAD

**Issue by Qee2** [yingDev/WGestures2-mac-bugs#91]
自从升级2.7.0及以后的版本后，经常出现这样的情况：点击了浏览器或其他软件的窗口顶部后，就会把这个窗口选中，移到鼠标，窗口也跟着移动。更换过电池了，没啥用。也不知道是不是鼠标本身出问题了。

**Comment by yingDev** [comment]
能否同时模式启动，然后出现问的时候把日志发给我？




YingDev
***@***.***




------------------ 原始邮件 ------------------
发件人: Qee2 ***@***.***&gt;
发送时间: 2021年11月24日 16:34
收件人: yingDev/WGestures2-bugs ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yingDev/WGestures2-bugs] 禁用了左键，但是经常出现双击并选中的操作 (Issue #91)





 
自从升级2.7.0及以后的版本后，经常出现这样的情况：点击了浏览器或其他软件的窗口顶部后，就会把这个窗口选中，移到鼠标，窗口也跟着移动。更换过电池了，没啥用。也不知道是不是鼠标本身出问题了。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yingDev** [comment]
有没有安装其它键鼠软件呢

**Comment by 1situzj** [comment]
系统版本 : win10 LTSC 1809
程序版本 : 2.7.1(但问题从 2.7.0 已存在)
补充 : 安装了其他键鼠软件(Quicker), 但卸载 Quicker 后再安装 WGestures 问题依旧存在

问题描述 : 自定义鼠标右键 + 左键执行快捷键 Alt + F4, 当通过这种方式执行后(不管有没有窗口被关闭), 把鼠标移动到任务栏, 左击任一窗口, 会有概率出现拖动窗口的现象(与执行快捷键后的时间无关), 该现象与按着鼠标左键拖动窗口一模一样！！！

问题猜测 ：自定义的快捷键最后为左键时，完成快捷键后，有概率没有释放鼠标左键

**Comment by yingDev** [comment]
@1situzj 未能重现. 
- 资源管理器有安装任何插件么?

**Comment by 1situzj** [comment]
资源管理器使用了 QTTabBar

**Comment by yingDev** [comment]
> 资源管理器使用了 QTTabBar

😃
另一个案例也安装了这个, 或许与之有关. 不过它不兼容 win11, 我暂时无法测试.

**Comment by yingDev** [comment]
@1situzj 能否加 Q 897 32209

**Comment by 1situzj** [comment]
现象汇总 :
    1. 卸载 QTTabBar 后重启, 问题依然存在
    2. 该现象不仅存在于资源管理器, 浏览器中也会出现这样的问题
    3(新发现). 将快捷键改为鼠标中键 + 右键时, 左键点击也会出现拖动的问题
    4(新发现). 按下鼠标右键后延时一下再按左键, 基本不会出现该问题

个人推测 :
    1. 快捷键的点击按键之间不能间隔太短

**Comment by 1situzj** [comment]
已发送好友申请

**Comment by yingDev** [comment]
没有收到呢... 897326609
- 白分浏览器? 迅捷 PDF ?
- 具体手势配置是怎样? 一定是在执行一个手势之后么? 如果手势什么也不做, 执行后如何?

**Comment by Qee2** [comment]
不好意思，太忙了。版本升级前后，我没有新装什么软件，键鼠用的是罗技优联无线键鼠。“同时模式启动”指的是啥呢？还有我是小白，不知道问题日志在哪里（笑哭）。这个问题一直存在，很影响体验。

**Comment by yingDev** [comment]
2.8已修复
